name: Test

on:
  workflow_run:
    workflows: [Echo]
    branches: [main, master]
    types: 
      - completed
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]

jobs:
  # Run unit-tests
  test-job:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: install
        run: |
          pip install -r requirements.txt

      - name: test
        run: |
          pytest
